if(NOT DEFINED FEM_FILE)
    message(FATAL_ERROR "FEM_FILE is required")
endif()

file(READ "${FEM_FILE}" fem_text)

if(fem_text MATCHES "__virtual_gap_[0-9]+")
else()
    message(FATAL_ERROR "Autogenerated virtual gap material not found in rewritten FEM file")
endif()

if(fem_text MATCHES "\\[NumBlockLabels\\][^\n]*= 2")
else()
    message(FATAL_ERROR "Expected rewritten FEM file to contain 2 block labels after virtual-gap expansion")
endif()

if(fem_text MATCHES "\\[NumSegments\\][^\n]*= 10")
else()
    message(FATAL_ERROR "Expected rewritten FEM file to contain 10 segments after virtual-gap expansion")
endif()
